version: "2"

run:
  timeout: 5m

linters:
  enable:
    # Seguridad
    - gosec

    # Calidad
    - revive
    - unconvert

    # Complejidad
    - gocyclo
    - cyclop
    
    # Performance
    - prealloc
    - perfsprint

    # SQL
    - sqlclosecheck

    # JSON
    - nilnil

    # Shadow variables
    - govet

    # Concurrencia
    - bodyclose

    # Logs
    - sloglint

    # Analisis estatico base
    - errcheck
    - staticcheck
    - ineffassign
    - unused

    # Calidad extendida
    - gocritic
  settings:
    goimports:
      local-prefixes: github.com/FrancoPersonal/golang-api-rest-aws

    gocyclo:
      min-complexity: 15

    cyclop:
      max-complexity: 15

    revive:
      rules:
        - name: exported
          disabled: true

issues:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports